contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://umcaruje.github.io/gegsite/"
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Femmuhely"
  author = "Gegsite"